# Generated by Django 5.2.17 on 2026-10-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_webhookdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='payments.payment')),
            ],
            options={
                'verbose_name_plural': 'Payment status histories',
                'ordering': ['changed_at'],
            },
        ),
    ]
